[versions]
graalvm = "24.2.1"

jtreesitter = "0.25.1"

junit = "5.9.0"

[libraries]
graal-sdk = { module = "org.graalvm.sdk:graal-sdk", version.ref = "graalvm" }
truffle-runtime = { module = "org.graalvm.truffle:truffle-runtime", version.ref = "graalvm" }

jtreesitter = { group = "io.github.tree-sitter", name = "jtreesitter", version.ref = "jtreesitter" }

truffle-api = { module = "org.graalvm.truffle:truffle-api", version.ref = "graalvm" }
truffle-dsl-processor = { module = "org.graalvm.truffle:truffle-dsl-processor", version.ref = "graalvm" }

junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
